insert into product (product_name, company_name, category, price, rating) values ('Galaxy F13', 'Samsung', 'Electronic', 20000, 3);
insert into product (product_name, company_name, category, price, rating) values ('Yeezy 450', 'Adidas', 'Fashion', 29999, 4.7);
insert into product (product_name, company_name, category, price, rating) values ('V23e', 'Vivo', 'Electronic', 24000, 4.9);
insert into product (product_name, company_name, category, price, rating) values ('TUF Gaming A17', 'Asus', 'Electronic', 50990, 3.9);
insert into product (product_name, company_name, category, price, rating) values ('C30', 'Realme', 'Electronic', 10000, 1);
insert into product (product_name, company_name, category, price, rating) values ('Storm Football', 'NIVIA', 'Sports', 399, 4);
insert into product (product_name, company_name, category, price, rating) values ('Astra Football', 'MARMAN', 'Sports', 450, 2.6);
insert into product (product_name, company_name, category, price, rating) values ('Slim fit shirt', 'Louis philippe', 'Fashion', 1300, 5);
insert into product (product_name, company_name, category, price, rating) values ('Mavis 350', 'Yonex', 'Sports', 1029, 2);
insert into product (product_name, company_name, category, price, rating) values ('Airpods 131Pro', 'Boat', 'Electronic', 1400, 3); 
insert into product (product_name, company_name, category, price, rating) values ('Rockerz510', 'Boat', 'Electronic', 1999, 5);
insert into product (product_name, company_name, category, price, rating) values ('S22', 'Samsung', 'Electronic', 52990, 4.5);
insert into product (product_name, company_name, category, price, rating) values ('VivoBook K15', 'Asus', 'Electronic', 55000, 5);
insert into product (product_name, company_name, category, price, rating) values ('Narzo50i', 'Realme', 'Electronic', 6542, 1.5);
insert into product (product_name, company_name, category, price, rating) values ('Beast Gym bag4', 'NIVIA', 'Sports', 1000, 3.8);
insert into product (product_name, company_name, category, price, rating) values ('T1','Vivo', 'Electronic', 15000, 4.3);
insert into product (product_name, company_name, category, price, rating) values ('X80 pro', 'Vivo', 'Electronic', 80000, 4.4);
insert into product (product_name, company_name, category, price, rating) values ('iphone 14', 'APPLE', 'Electronic', 67999, 5);
insert into product (product_name, company_name, category, price, rating) values ('iphone 11', 'APPLE', 'Electronic', 38000, 4.8);
insert into product (product_name, company_name, category, price, rating) values ('Air Jordan 1 Retro High OG', 'Nike', 'Fashion', 17000, 4.5);